### ISSUE TITLE
Block Syncing Error

### ISSUE THREAD

**Issue by eshangui** [qtumproject/qtuminfo#18]
chain: regtest
[2019-08-30T09:51:49.754Z] info: Block Service: download progress: 4800/11746 (40.8650%)
[2019-08-30T09:51:54.755Z] info: Block Service: download progress: 4864/11746 (41.4098%)
[2019-08-30T09:51:59.756Z] info: Block Service: download progress: 4927/11746 (41.9462%)
[2019-08-30T09:52:04.757Z] info: Block Service: download progress: 4993/11746 (42.5081%)
[2019-08-30T09:52:05.395Z] error: Block Service: handle error TypeError: Cannot read property 'addressId' of null
    at BlockService.__onBlock (/home/explorer/qtum/qtuminfo/node/services/block.js:414:9)
    at async BlockService._saveBlock (/home/explorer/qtum/qtuminfo/node/services/block.js:360:7)

**Comment by eshangui** [comment]
I have cleared the whole db and restart for several times, but still the same error, does all the 3 projects support regtest chain? (It seems regtest is not defined in [qtuminfo-ui/utils/network.js](https://github.com/qtumproject/qtuminfo-ui/blob/master/utils/network.js))

**Comment by xuanyan0x7c7** [comment]
Fixed a475839966889ed4a2b534b1acb6b4c0addb4c87
